services: # （１）
  env:
    image: signate
    container_name: signate_contadiner
    volumes: # （４）
      - ..:/root/work
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
